version: "3.9"
services:
  GestionProduit:
    container_name: "ProductContainertwo"
    image: "productimagetwo"
    build: .\MicroServiceACMM\ChaimaIdoudi
    ports:
      - "8088:8081"
    depends_on:
      - db-mysql

  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Ms_Produit
    ports:
      - "3306:3306"
    restart: unless-stopped