version: '3'

services:
  user:
    container_name: user
    image: "user"
    build: ./user
    ports:
      - 8091:8091
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - "eureka"

  eureka:
    container_name: eureka
    build: ./eureka
    hostname: eureka
    image: "eureka"
    ports:
      - 8761:8761
