spring:
 cloud:
   gateway:
     routes:
       - id: user
         uri: http://localhost:8091
         predicates:
           - Path=/user/**
       - id: avis
         uri: http://localhost:8000
         predicates:
           - Path=/avis/**



 application:
   name: gateway

 security:
   oauth2:
     resourceserver:
       jwt:
         issuer-uri: http://localhost:9090/realms/microservice
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
jwt:
  auth:
    converter:
      resource-id: gateway
      principle-attribute: preferred_username
